logspout:
    image: bekt/logspout-logstash
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    links:
     - logstash
    environment:
        ROUTE_URIS: logstash://logstash:5000
        RETRY_SEND: "true"
        RETRY_STARTUP: "true"

logstash:
    image: logstash:6.8.5
    volumes:
     - ./logstash/pipline/logstash.conf:/etc/logstash.conf
     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    links:
     - elasticsearch
    environment:
        LOGSPOUT: ignore
    command: -f /etc/logstash.conf

elasticsearch:
    image: elasticsearch:6.8.5
    environment:
        LOGSPOUT: ignore

kibana:
    image: kibana:6.8.5
    environment:
        LOGSPOUT: ignore
        ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
     - elasticsearch
    ports:
     - "5601:5601"
